services:
  backend:
    build:
      context: ./backend
    container_name: asset_backend
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: asset_frontend
    ports:
      - "5173:80"     # ✅ ONE PORT for website + API
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
